### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by ibrahim5253** [stephenbach/bach-uai13-code#1]
Hi,

I was trying to execute `runCollectiveClassification.sh`, but it keeps throwing the following error message:

    [ERROR] Failed to execute goal on project bach-uai13-code: Could not resolve dependencies for project edu.umd.cs:bach-uai13-code:jar:1.0-SNAPSHOT: Failed to collect dependencies at edu.umd.cs:psl-groovy:jar:1.1: Failed to read artifact descriptor for edu.umd.cs:psl-groovy:jar:1.1: Could not transfer artifact edu.umd.cs:psl-groovy:pom:1.1 from/to psl-releases (https://scm.umiacs.umd.edu/maven/lccd/content/repositories/psl-releases/): Failed to transfer file: https://scm.umiacs.umd.edu/maven/lccd/content/repositories/psl-releases/edu/umd/cs/psl-groovy/1.1/psl-groovy-1.1.pom. Return code is: 503 , ReasonPhrase:Service Unavailable. -> [Help 1] 

Seems like a missing dependency which is apparently no longer available. Maybe the PSL version is deprecated? What can be done?

PS: I am not even able to install PSL. `mvn compile` in the PSL root directory throws,

    [ERROR] Failed to execute goal on project psl-core: Could not resolve dependencies for project edu.umd.cs:psl-core:jar:1.2: Failed to collect dependencies at edu.emory.mathcs:parallelcolt:jar:0.9.4: Failed to read artifact descriptor for edu.emory.mathcs:parallelcolt:jar:0.9.4: Could not transfer artifact edu.emory.mathcs:parallelcolt:pom:0.9.4 from/to psl-releases (https://scm.umiacs.umd.edu/maven/lccd/content/repositories/psl-releases/): Failed to transfer file: https://scm.umiacs.umd.edu/maven/lccd/content/repositories/psl-releases/edu/emory/mathcs/parallelcolt/0.9.4/parallelcolt-0.9.4.pom. Return code is: 503 , ReasonPhrase:Service Unavailable. -> [Help 1]

Checking out any other version doesn't help either.

(64-Bit Gentoo Linux 2.2)

**Comment by stephenbach** [comment]
Hi! Those repos have been taken down now that LINQS moved to UCSC. I've updated the pointers in `pom.xml` and the artifacts download correctly.

Btw, it was written for Java 6. It looks like it doesn't compile on later versions of Java.  Please let me know if you see other issues. Thanks!
